### ISSUE TITLE
omniauth: (slack) Authentication failure! csrf_detected: OmniAuth::Strategies::OAuth2::CallbackError, csrf_detected | CSRF detected

### ISSUE THREAD

**Issue by danielschwartz** [kmrshntr/omniauth-slack#29]
I get the above error on a totally vanilla setup with Devise. I've tried submitting the CSRF token as the state and that does not fix the issue either. The link the slack button sends users to is: `https://slack.com/oauth/authorize?scope=identify&client_id=<client_id>`

Any help would be appreciated.

**Comment by danielschwartz** [comment]
Fixed this. Was incorrectly generating the link.

**Comment by romanos** [comment]
Hey @danielschwartz, I still get this issue. Just wanted to say hi though.

**Comment by danielschwartz** [comment]
Oh hai @romanos  😀. I can look into my internal monkey patch that I made to see if it helps. Remind me some time next week and I’ll create a gist for you.

**Comment by romanos** [comment]
Thanks dude, it's all good. Already solved it, just thought it was funny to see you here 🍺
